apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-pipelineresource
spec:
  type: git
  params:
    - name: deleteExisting
      value: "true"
    - name: revision
      value: main
    - name: url
      value: # mygithub url