apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-pipelinerun
spec:
  resources:
    - name: git-pipelineresource
      resourceRef:
        name: git-pipelineresource
  workspaces:
  - name: tekton-pvc
    persistentvolumeclaim:
      claimName: efs-pvc
  serviceAccountName: my-sa
  pipelineRef:
    name: test-pipeline
