apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-container-and-push
spec:

  workspaces:
  - name: tekton-pvc
  params:
    - name: commitshashort
      type: string
  steps:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      workingDir: $(workspaces.tekton-pvc.path)
      args:
        - --dockerfile=$(workspaces.tekton-pvc.path)/Dockerfile
        - --destination=mokpolar/tekton-pipeline-test:$(params.commitshashort)
        - --context=$(workspaces.tekton-pvc.path)
      volumeMounts:
        - name: my-secret
          mountPath: /kaniko/.docker/
  volumes:
    - name: my-secret
      secret:
        secretName: my-secret
        items:
        - key: .dockerconfigjson
          path: config.json
